export const data = [
  {
    id: 1,
    code: "700750V",
    name: 'Anti-vacuum Valve - 1/4"',
    genuine: true,
    recommended: false,
    price: "£10.00",
    img: "./images/valve.png",
  },
  {
    id: 2,
    code: "700750V",
    name: 'Anti-vacuum Valve - 1/4"',
    genuine: false,
    recommended: false,
    price: "£10.00",
    img: "./images/valve.png",
  },
  {
    id: 3,
    code: "700750V",
    name: 'Anti-vacuum Valve - 1/4"',
    genuine: true,
    recommended: true,
    price: "£10.00",
    img: "./images/valve.png",
  },
  {
    id: 4,
    code: "700750V",
    name: 'Anti-vacuum Valve - 1/4"',
    genuine: true,
    recommended: false,
    price: "£10.00",
    img: "./images/valve.png",
  },
  {
    id: 5,
    code: "700750V",
    name: 'Anti-vacuum Valve - 1/4"',
    genuine: true,
    recommended: true,
    price: "£10.00",
    img: "./images/valve.png",
  },
  {
    id: 6,
    code: "700750V",
    name: 'Anti-vacuum Valve - 1/4"',
    genuine: false,
    recommended: false,
    price: "£10.00",
    img: "./images/valve.png",
  },
  {
    id: 7,
    code: "700750V",
    name: 'Anti-vacuum Valve - 1/4"',
    genuine: true,
    recommended: false,
    price: "£10.00",
    img: "./images/valve.png",
  },
  {
    id: 8,
    code: "700750V",
    name: 'Anti-vacuum Valve - 1/4"',
    genuine: true,
    recommended: false,
    price: "£10.00",
    img: "./images/valve.png",
  },
  {
    id: 9,
    code: "700750V",
    name: 'Anti-vacuum Valve - 1/4"',
    genuine: true,
    recommended: true,
    price: "£10.00",
    img: "./images/valve.png",
  },
  {
    id: 10,
    code: "700750V",
    name: 'Anti-vacuum Valve - 1/4"',
    genuine: true,
    recommended: true,
    price: "£10.00",
    img: "./images/valve.png",
  },
  {
    id: 11,
    code: "700750V",
    name: 'Anti-vacuum Valve - 1/4"',
    genuine: false,
    recommended: false,
    price: "£10.00",
    img: "./images/valve.png",
  },
  {
    id: 12,
    code: "700750V",
    name: 'Anti-vacuum Valve - 1/4"',
    genuine: true,
    recommended: false,
    price: "£10.00",
    img: "./images/valve.png",
  },
];
